# Generated by Django 5.0.1 on 2024-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('datetimes', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=10000)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Subject', models.CharField(default=' Subject', max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('datetimes', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
